### ISSUE TITLE
mention of "dice" seems to be a typo

### ISSUE THREAD

**Issue by witchlane** [learn-co-curriculum/dsc-1-08-11-permutations-and-factorials#3]
"dice" is mentioned once randomly in this sentence - i would think it needs to be removed.  
![image](https://user-images.githubusercontent.com/44211854/51789796-c6f18100-215a-11e9-90ad-42e89f8982b8.png)

**Comment by LoreDirick** [comment]
correct! @witchlane. fixed and will be rolled out soon.
